#!/bin/sh /etc/rc.common
START=94

LOGFILE=/tmp/provision.log

start() {
    DATE=`date`
    echo "Tried to start provisioning on $DATE" >> $LOGFILE
    /www/cgi-bin/provision /tmp/provision.log   >> $LOGFILE
}

stop() {
    echo "Tried to stop provisioning on $DATE" >> $LOGFILE
}

