#!/bin/bash

# read & parse query
QUERY=$QUERY_STRING
if [ "$REQUEST_METHOD" = "POST" ]; then
    read POST_QUERY
fi

DATA=`echo "$POST_QUERY" | grep -oE "(^|[?&])data=[^&]+" | sed "s/%20/ /g" | cut -f 2- -d "="`
TYPE=`echo "$POST_QUERY" | grep -oE "(^|[?&])type=[^&]+" | sed "s/%20/ /g" | cut -f 2- -d "="`

echo "Content-type: " $TYPE | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | xargs echo -e
echo
echo $DATA | sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | sed 's/+/ /g' | xargs echo -e
