# New ports collection makefile for:	json-c
# Date created:				June 23 2006
# Whom:					gno@yahoo-inc.com
#
# $FreeBSD: ports/devel/json-c/Makefile,v 1.3 2008/04/19 17:47:48 miwi Exp $
#

PORTNAME=	json-c
PORTVERSION=	0.9
CATEGORIES=	devel
MASTER_SITES=	http://oss.metaparadigm.com/json-c/

MAINTAINER=	gno@yahoo-inc.com
COMMENT=	A JSON (Javascript Object Notation) implementation in C

USE_LDCONFIG=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes

.include <bsd.port.mk>
